[http.middlewares]
  [http.middlewares.authelia.forwardAuth]
    address = "http://authelia:9091/api/verify?rd=https://authelia.<your_domain>"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups"]
