#[http.routers.api]
#    entryPoints = ["traefik"]
#    rule = "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
#    service = "api@internal"
#    middlewares = ["basic_auth"]

[http.middlewares]
  [http.middlewares.basic_auth.basicAuth]
  ### API Login: test/test ###
    users = [
      "test:$apr1$Ws2zxCMW$zCxeZDJVWdpX6STbkEbty/",
    ]
