# CSP for VNC: https://github.com/cockpit-project/cockpit/pull/5932

[http.middlewares]
  [http.middlewares.vnc-headers-nocookie.headers]
    SSLRedirect = true
    SSLForceHost = true
    STSSeconds = 315360000
    STSIncludeSubdomains = true
    STSPreload = true
    ForceSTSHeader = true
    FrameDeny = true
    CustomFrameOptionsValue = "SAMEORIGIN"
    ContentTypeNosniff = true
    BrowserXssFilter = true
    ContentSecurityPolicy = "default-src 'self' 'unsafe-inline' data:; frame-ancestors 'self'; object-src 'none'; base-uri 'none'"
    ReferrerPolicy = "same-origin"
    FeaturePolicy = "camera 'none'; display-capture 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none'"
    [http.middlewares.vnc-headers-nocookie.headers.customResponseHeaders]
      X-Robots-Tag = "none,noarchive,nosnippet,notranslate,noimageindex"
