version: "3.7"
services:

## Docker Swarm Visualizer

  viz:
    image: hypriot/visualizer:linux-armv7
    networks:
      - overlay_net
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
#      mode: global # service runs on every node
      mode: replicated # a specified number of containers (default)
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
          - node.platform.arch == armv7l

networks:
  overlay_net:
    external: true
