version: "3.7"
services:

## Airsonic - Music Server
  # Login: admin / admin

  airsonic:
    container_name: airsonic
    image: linuxserver/airsonic:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "4040:4040"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /mnt/storage/music/music:/music:ro
      - $USERDIR/docker/airsonic/podcasts:/podcasts
      - $USERDIR/docker/airsonic/playlists:/playlists
      - $USERDIR/docker/airsonic/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - JAVA_OPTS=-Dserver.use-forward-headers=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.airsonic-rtr.entrypoints=https"
      - "traefik.http.routers.airsonic-rtr.rule=Host(`airsonic.$DOMAINNAME`)"
      - "traefik.http.routers.airsonic-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.airsonic-rtr.middlewares=airsonic-headers"
      - "traefik.http.middlewares.airsonic-headers.headers.accesscontrolallowmethods=GET, OPTIONS, PUT"
      - "traefik.http.middlewares.airsonic-headers.headers.accesscontrolalloworiginlist=https://$DOMAINNAME"
      - "traefik.http.middlewares.airsonic-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.airsonic-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.airsonic-headers.headers.allowedhosts=airsonic.$DOMAINNAME"
      - "traefik.http.middlewares.airsonic-headers.headers.hostsproxyheaders=X-Forwarded-Host"
      - "traefik.http.middlewares.airsonic-headers.headers.sslredirect=true"
      - "traefik.http.middlewares.airsonic-headers.headers.sslhost=airsonic.$DOMAINNAME"
      - "traefik.http.middlewares.airsonic-headers.headers.sslforcehost=true"
      - "traefik.http.middlewares.airsonic-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.airsonic-headers.headers.stsseconds=63072000"
      - "traefik.http.middlewares.airsonic-headers.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.airsonic-headers.headers.stspreload=true"
      - "traefik.http.middlewares.airsonic-headers.headers.forcestsheader=true"
#      - "traefik.http.middlewares.airsonic-headers.headers.framedeny=true"
      - "traefik.http.middlewares.airsonic-headers.headers.customframeoptionsvalue=SAMEORIGIN" # This option overrides FrameDeny
      - "traefik.http.middlewares.airsonic-headers.headers.contenttypenosniff=true"
      - "traefik.http.middlewares.airsonic-headers.headers.browserxssfilter=true"
#      - "traefik.http.middlewares.airsonic-headers.headers.contentsecuritypolicy=frame-ancestors 'none'; object-src 'none'; base-uri 'none';"
#      - traefik.http.middlewares.airsonic-headers.headers.ContentSecurityPolicy="default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.gstatic.com; img-src 'self' *.akamaized.net; style-src 'self' 'unsafe-inline' fonts.googleapis.com; font-src 'self' fonts.gstatic.com; frame-src 'self'; object-src 'none'; base-uri 'none';"
      - "traefik.http.middlewares.airsonic-headers.headers.referrerpolicy=same-origin"
      - "traefik.http.middlewares.airsonic-headers.headers.featurepolicy=camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
      - "traefik.http.middlewares.airsonic-headers.headers.customresponseheaders.X-Robots-Tag=none,noarchive,nosnippet,notranslate,noimageindex,"
      ## HTTP Services
      - "traefik.http.routers.airsonic-rtr.service=airsonic-svc"
      - "traefik.http.services.airsonic-svc.loadbalancer.server.port=4040"
      ## Web Login - Forward Auth
      - "traefik.http.routers.airsonicLogin-rtr.entrypoints=https"
      - "traefik.http.routers.airsonicLogin-rtr.rule=(Host(`airsonic.$DOMAINNAME`) && Path(`/login`))"
      - "traefik.http.routers.airsonicLogin-rtr.priority=20"
      - "traefik.http.routers.airsonicLogin-rtr.middlewares=authelia@file"
      - "traefik.http.routers.airsonicLogin-rtr.service=airsonic-svc"


networks:
  traefik_proxy:
    external: true
