version: "3.7"
services:

## Airsonic - Music Server
  # Login: admin / admin

  airsonic:
    container_name: airsonic
    image: linuxserver/airsonic
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "4040:4040"
    volumes:
      - /mnt/storage/music/music:/music:ro
      - $USERDIR/docker/airsonic/podcasts:/podcasts
      - $USERDIR/docker/airsonic/playlists:/playlists
      - $USERDIR/docker/airsonic/config:/config
#      - $USERDIR/docker/airsonic/config:/app/airsonic/config #Used to change log level for debugging
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - JAVA_OPTS="-Dserver.use-forward-headers=true -Dserver.tomcat.protocol-header=X-Forwarded-Proto"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.airsonic.entrypoints=https
      - traefik.http.routers.airsonic.rule=Host(`airsonic.$DOMAINNAME`)
      - traefik.http.routers.airsonic.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.airsonic.middlewares=airsonic-headers
      - traefik.http.middlewares.airsonic-headers.headers.SSLHost=airsonic.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.airsonic.middlewares=noauth-chain-nocookie@file
      ## Services
      - traefik.http.routers.airsonic.service=airsonic
      - traefik.http.services.airsonic.loadbalancer.server.port=4040

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
