version: "3.7"
services:

## Authelia - Self-Hosted Single Sign-On and Two-Factor Authentication
  # Configuration files at: https://github.com/authelia/authelia/tree/master/compose/lite
  # I used this to create my jwt_secret: https://www.grc.com/passwords.htm
  # Create new hashed password: docker run authelia/authelia:latest authelia hash-password <new_password>

  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "9091:9091"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/authelia:/config
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=https"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=rate-limit@file,secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"

networks:
  traefik_proxy:
    external: true
