version: "3.7"
services:

## Autoindex - Simple Directory Index
  autoindex:
    container_name: autoindex
    image: chauffer/nginx-autoindex:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    volumes:
      - $TESTDIR:/usr/share/nginx/html:ro # Location you want to index
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.autoindex-rtr.entrypoints=https"
      - "traefik.http.routers.autoindex-rtr.rule=Host(`autoindex.$DOMAINNAME`)"
      - "traefik.http.routers.autoindex-rtr.tls=true"
      - "traefik.http.routers.autoindex-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.autoindex-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.autoindex-rtr.service=autoindex-svc"
      - "traefik.http.services.autoindex-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
