version: "3.7"
services:

## Paste Bin

  ## Change the theme:
    # sudo vim $USERDIR/docker/bin/cfg/conf.php
    # change template = "bootstrap" to "bootstrap-dark-page"
  ## Other options: https://privatebin.info/screenshots.html

  bin:
    container_name: bin
    image: jgeusebroek/privatebin:latest
    restart: always
    networks:
      - traefik_proxy
      - mariadb
#    ports:
#     - "80:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/bin/data:/privatebin/data
      - $USERDIR/docker/bin/cfg:/privatebin/cfg
    environment:
      - UID=$PUID
      - GID=$PGID
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bin-rtr.entrypoints=https"
      - "traefik.http.routers.bin-rtr.rule=Host(`bin.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.bin-rtr.middlewares=secure-headers@file,rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.bin-rtr.service=bin-svc"
      - "traefik.http.services.bin-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
