version: "3.7"
services:

## Stikked - A Paste Bin

  ## Suggested procedure to create your Stikked Database:
  ## Change the <password>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE bin CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
    # GRANT ALL PRIVILEGES ON bin.* TO 'bin'@'bin.mariadb' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  bin:
    container_name: bin
    image: claudehohl/stikked:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
      - mariadb
#    ports:
#     - "80:80"
    security_opt:
      - no-new-privileges:true
    environment:
      - STIKKED_SITE_NAME=$DOMAINNAME PasteBin
      - STIKKED_BASE_URL=https://bin.$DOMAINNAME
      - STIKKED_DB_HOSTNAME=mariadb
      - STIKKED_DB_DATABASE=bin
      - STIKKED_DB_USERNAME=bin
      - STIKKED_DB_PASSWORD=$MYSQL_PASSWORD
      - STIKKED_THEME=bootstrap
      - STIKKED_JS_EDITOR=ace #codemirror
      - STIKKED_DISALLOW_SEARCH_ENGINES=true
      - STIKKED_URL_SHORTENING_USE=yourls
      - STIKKED_YOURLS_URL=https://$DOMAINNAME
      - STIKKED_YOURLS_SIGNATURE=$YOURLS_API
      - STIKKED_RECAPTCHA_PUBLICKEY=$RECAPTCHA_PUBLICKEY
      - STIKKED_RECAPTCHA_PRIVATEKEY=$RECAPTCHA_PRIVATEKEY
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bin-rtr.entrypoints=https"
      - "traefik.http.routers.bin-rtr.rule=Host(`bin.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.bin-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.bin-rtr.service=bin-svc"
      - "traefik.http.services.bin-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
