version: "3.7"
services:

## Bitwarden - Password Vault
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server:latest
    restart: always
    networks:
      - traefik_proxy
      - bw-net
#    ports:
#      - "80:80"
#      - "3012:3012"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/bitwarden:/data
      - /var/log/docker:/var/log/docker
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SIGNUPS_ALLOWED=false # Change to false after first login
      - INVITATIONS_ALLOWED=true # Send invitation using admin page
      - WEBSOCKET_ENABLED=true
      - LOG_FILE=/var/log/docker/bitwarden.log
      - SMTP_HOST=protonmail-bridge
      - SMTP_FROM=$PROTONMAIL_USER
      - SMTP_PORT=25
      - SMTP_SSL=false
      - SMTP_USERNAME=$PROTONMAIL_USER
      - SMTP_PASSWORD=$PROTONMAIL_PASS
      - DOMAIN=https://bitwarden.$DOMAINNAME
#      - DISABLE_ADMIN_TOKEN=true ### USE WITH CAUTION!! Access admin page at bitwarden.$DOMAINNAME/admin to send invitations - anyone can access, add authorization!!!
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bitwarden-rtr.entrypoints=https"
      - "traefik.http.routers.bitwarden-rtr.rule=Host(`bitwarden.$DOMAINNAME`)"
      - "traefik.http.routers.bitwarden-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.bitwarden-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.bitwarden-rtr.service=bitwarden-svc"
      - "traefik.http.services.bitwarden-svc.loadbalancer.server.port=80"
      ## Bitwarden WebSocket
      - "traefik.http.routers.bitwardenHub-rtr.entrypoints=https"
      - "traefik.http.routers.bitwardenHub-rtr.rule=Host(`bitwarden.$DOMAINNAME`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwardenHub-rtr.priority=20"
      - "traefik.http.routers.bitwardenHub-rtr.service=bitwardenHub-svc"
      - "traefik.http.services.bitwardenHub-svc.loadbalancer.server.port=3012"
      ## Admin Page
      - "traefik.http.routers.bitwardenAdmin-rtr.entrypoints=https"
      - "traefik.http.routers.bitwardenAdmin-rtr.rule=(Host(`bitwarden.$DOMAINNAME`) && Path(`/admin/`))"
      - "traefik.http.routers.bitwardenAdmin-rtr.priority=20"
      - "traefik.http.routers.bitwardenAdmin-rtr.middlewares=secure-chain@file"
      - "traefik.http.routers.bitwardenAdmin-rtr.service=bitwarden-svc"

## Bitwarden Backup

  ## To restore database from backup:
    # docker exec -it bitwarden bash
    # mv /data/db.sqlite3 /data/db.sqlite3.back
    # sqlite3 /data/db.sqlite3 ".restore '/data/db-backup/select_db_file'"
    # exit

  bw_backup:
    container_name: bw_backup
    image: bruceforce/bw_backup
    restart: on-failure
    networks:
      - bw-net
    security_opt:
      - no-new-privileges:true
    init: true
    depends_on:
      - bitwarden
    volumes:
      - $USERDIR/docker/bitwarden:/data
      - /mnt/storage/misc/backup/backup_databases/bitwarden:/dbbackup
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_FILE=/data/db.sqlite3
      - BACKUP_FILE=/dbbackup/backup.sqlite3
      - CRON_TIME=30 4 * * *
      - TIMESTAMP=true
      - UID=0
      - GID=0

networks:
  traefik_proxy:
    external: true
  bw-net:
    external: false
