version: '2'
services:

## CryptPad - A Zero-Knowledge realtime collaborative editor
  cryptpad:
    container_name: cryptpad
    image: "promasu/cryptpad:latest"
    restart: unless-stopped
    networks:
      - traefik_proxy
#    ports:
#     - "3000:3000"
#     - "3001:3001"
#    security_opt:
#      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    volumes:
      - $USERDIR/docker/cryptpad/config/config.js:/cryptpad/config/config.js
#      - $USERDIR/docker/cryptpad/customize:/cryptpad/customize
      - cryptpad_data:/cryptpad
#      - $USERDIR/docker/cryptpad/data/blob:/cryptpad/blob
#      - $USERDIR/docker/cryptpad/data/block:/cryptpad/block
#      - $USERDIR/docker/cryptpad/data/data:/cryptpad/data
#      - $USERDIR/docker/cryptpad/data/files:/cryptpad/datastore
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.cryptpad-rtr.entrypoints=https"
      - "traefik.http.routers.cryptpad-rtr.rule=HostHeader(`cryptpad.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.cryptpad-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.cryptpad-rtr.service=cryptpad-svc"
      - "traefik.http.services.cryptpad-svc.loadbalancer.server.port=3000"
      ## Sandbox
      - "traefik.http.routers.cryptpad-sandbox-rtr.entrypoints=https"
      - "traefik.http.routers.cryptpad-sandbox-rtr.rule=HostHeader(`cryptpad-sandbox.$DOMAINNAME`)"
      - "traefik.http.routers.cryptpad-sandbox-rtr.middlewares=secure-chain@file"
      - "traefik.http.routers.cryptpad-sandbox-rtr.service=cryptpad-sandbox-svc"
      - "traefik.http.services.cryptpad-sandbox-svc.loadbalancer.server.port=3001"

volumes:
  cryptpad_data:

networks:
  traefik_proxy:
    external: true
