version: '3.7'
services:

## DashMachine - Bookmark Dashboard
  dashmachine:
    container_name: dashmachine
    image: rmountjoy/dashmachine:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - 5000:5000
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/dashmachine:/dashmachine/dashmachine/user_data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.dashmachine-rtr.entrypoints=https"
      - "traefik.http.routers.dashmachine-rtr.rule=Host(`dash.${DOMAINNAME}`)"
      ## Middlewares
      - "traefik.http.routers.dashmachine-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.dashmachine-rtr.service=dashmachine-svc"
      - "traefik.http.services.dashmachine-svc.loadbalancer.server.port=5000"

networks:
  traefik_proxy:
    external: true
