version: "3.7"
services:

## FreshRSS

  ## Suggested procedure to create your Database:
  ## Change the <password>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE freshrss CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON freshrss.* TO 'freshrss'@'freshrss.mariadb' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  freshrss:
    container_name: freshrss
    image: linuxserver/freshrss:latest
    restart: always
    networks:
      - traefik_proxy
      - mariadb
#    ports:
#      - "80:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/freshrss:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
