version: "3.7"
services:

## Grafana
  grafana:
    user: "$PUID"
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "3000:3000"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/grafana/data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.grafana-rtr.entrypoints=https"
      - "traefik.http.routers.grafana-rtr.rule=Host(`grafana.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.grafana-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.grafana-rtr.service=grafana-svc"
      - "traefik.http.services.grafana-svc.loadbalancer.server.port=3000"

networks:
  traefik_proxy:
    external: true
