version: "3.7"
services:

## grocy - Web-based Groceries & Household Management

  # Give it a minute to start...
  # Login: admin / admin
  # Create new user and delete admin

  grocy:
    container_name: grocy
    image: linuxserver/grocy:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#     - "80:80"
    security_opt:
      - no-new-privileges:true
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.grocy-rtr.entrypoints=https"
      - "traefik.http.routers.grocy-rtr.rule=HostHeader(`grocy.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.grocy-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.grocy-rtr.service=grocy-svc"
      - "traefik.http.services.grocy-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
