version: "3.7"
services:

## Home Assistant - Home Automation Hub
  hass:
    container_name: hass
    image: homeassistant/home-assistant
    restart: always
    privileged: true
    networks:
      - traefik_proxy
#    ports:
#      - "8123:8123"
    volumes:
      - $USERDIR/docker/hass:/config
    environment:
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.hass.entrypoints=https
      - traefik.http.routers.hass.rule=Host(`hass.$DOMAINNAME`)
      - traefik.http.routers.hass.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.hass.middlewares=hass-headers
      - traefik.http.middlewares.hass-headers.headers.SSLHost=hass.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.hass.middlewares=noauth-chain@file
      ## Services
      - traefik.http.routers.hass.service=hass
      - traefik.http.services.hass.loadbalancer.server.port=8123

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
