version: "3.7"
services:

## Home Assistant - Home Automation Hub

  ## Check config with:
    # docker exec -it hass hass --script check_config -c /config

  hass:
    container_name: hass
    image: homeassistant/home-assistant:latest
    restart: always
#    privileged: true
    networks:
      - traefik_proxy
      - mqtt
#    ports:
#      - "8123:8123"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/hass:/config
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.hass-rtr.entrypoints=https"
      - "traefik.http.routers.hass-rtr.rule=Host(`hass.$DOMAINNAME`)"
#      - "traefik.http.routers.hass-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.hass-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.hass-rtr.service=hass-svc"
      - "traefik.http.services.hass-svc.loadbalancer.server.port=8123"
      ## API
#      - "traefik.http.routers.hassAPI-rtr.entrypoints=https"
#      - "traefik.http.routers.hassAPI-rtr.rule=HeadersRegexp(`User-Agent`, `Tautulli`)"
##      - "traefik.http.routers.hassAPI-rtr.rule=HeadersRegexp(`X-Forwarded-Uri`, `$REGEXPRRR`)"
#      - "traefik.http.routers.hassAPI-rtr.priority=20"
#      - "traefik.http.routers.hassAPI-rtr.middlewares=secure-headers@file"
#      - "traefik.http.routers.hassAPI-rtr.service=tautulli-svc"


networks:
  traefik_proxy:
    external: true
  mqtt:
    external: true
