version: "3.7"
services:

## Simple Directory Index / File Browser
  index:
    container_name: index
    image: corfr/h5ai:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/tmpfldr:/var/www/:ro # Location you want to index
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.index-rtr.entrypoints=https"
      - "traefik.http.routers.index-rtr.rule=Host(`index.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.index-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.index-rtr.service=index-svc"
      - "traefik.http.services.index-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
