version: "3.7"
services:

## iperf3 - Network Latency Tool
  iperf:
    container_name: iperf
    image: mlabbe/iperf3:latest
    restart: always
    networks:
      traefik_proxy:
        ipv4_address: 192.168.50.199
    ports:
      - "5201:5201/tcp"
      - "5201:5201/udp"
    security_opt:
      - no-new-privileges:true

networks:
  traefik_proxy:
    external: true
