version: "3.7"
services:

## Forward Authentication for Traefik
#  oauth:
#    container_name: oauth
##    image: thomseddon/traefik-forward-auth # thomseddeon's image doesnt support OIDC_ISSUER yet
#    image: funkypenguin/traefik-forward-auth:latest
#    restart: always
#    networks:
#      - traefik_proxy
#    depends_on:
#      - keycloak
#    environment:
#      - CLIENT_ID=$AUTH_CLIENT_ID
#      - CLIENT_SECRET=$AUTH_CLIENT_SECRET
#      - SECRET=$AUTH_SECRET
#      - OIDC_ISSUER=https://keycloak.$DOMAINNAME/auth/realms/$KEYCLOAK_REALM
#      - AUTH_HOST=oauth.$DOMAINNAME
#      - COOKIE_DOMAIN=$DOMAINNAME
#      - COOKIE_SECURE=true
#      - LIFETIME=2592000 # 30 days
#    labels:
#      - "traefik.enable=true"
#      ## HTTP Routers
#      - "traefik.http.routers.oauth-rtr.entrypoints=https"
#      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.$DOMAINNAME`)"
#      - "traefik.http.routers.oauth-rtr.tls=true"
#      - "traefik.http.routers.oauth-rtr.tls.certresolver=dns-cloudflare"
#      ## Middlewares
#      - "traefik.http.routers.oauth-rtr.middlewares=secure-chain@file,rate-limit@file"
#      ## HTTP Services
#      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
#      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"

## Keycloak - Private Authentication

  ## To fix net.core.*mem issues add these to the bottom of /etc/sysctl.conf
  ## https://forums.docker.com/t/how-to-tune-kernel-properties-in-docker-images/25291
    # ## Allow a 25MB UDP receive buffer for JGroups
    # net.core.rmem_max = 26214400
    # ## Allow a 1MB UDP send buffer for JGroups
    # net.core.wmem_max = 1048576

    # or

    # sudo sysctl -w net.core.rmem_max=26214400
    # sudo sysctl -w net.core.wmem_max=1048576
    ## https://www.cyberciti.biz/faq/reload-sysctl-conf-on-linux-using-sysctl/

  ## Suggested procedure to create your KeyCloak Database:
  ## Change the <password>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE keycloak CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
    # GRANT ALL PRIVILEGES ON keycloak.* TO 'keycloak'@'keycloak.mariadb' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  ## Initialize admin account:
    # docker exec keycloak keycloak/bin/add-user-keycloak.sh -u <username> -p <password>

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    restart: always
    networks:
      - traefik_proxy
      - mariadb
#    ports:
#      - "8080:8080"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - KEYCLOAK_USER=$MY_USERNAME
      - KEYCLOAK_PASSWORD=$MY_PASSWORD
      - DB_VENDOR=mariadb
      - DB_ADDR=mariadb
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=$MYSQL_PASSWORD
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=keycloak.$DOMAINNAME
#      - JDBC_PARAMS=connectTimeout=30000
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.keycloak-rtr.entrypoints=https"
      - "traefik.http.routers.keycloak-rtr.rule=Host(`keycloak.$DOMAINNAME`)"
      - "traefik.http.routers.keycloak-rtr.tls=true"
      - "traefik.http.routers.keycloak-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.keycloak-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.keycloak-rtr.service=keycloak-svc"
      - "traefik.http.services.keycloak-svc.loadbalancer.server.port=8080"

networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
