version: "3.7"
services:

# mosquitto_sub -h 192.168.1.50 -u username -P password -t "dev/test"
# mosquitto_pub -d -h 192.168.1.50 -u username -P password -t dev/test -m "Hello World"

# use -t "#" for "all" topics

## Mosquitto - MQTT Broker
  mosquitto:
    user: $PUID:$PGID
    container_name: mosquitto
    image: toke/mosquitto:latest
    restart: always
    networks:
      - mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/mosquitto/config:/mqtt/config
      - $USERDIR/docker/mosquitto/log:/mqtt/log
      - $USERDIR/docker/mosquitto/data/:/mqtt/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  mqtt:
    external: true
