version: "3.7"
services:

## MQTT Broker
  mqtt:
    container_name: mqtt
    image: matteocollina/mosca:latest
    restart: always
    networks:
      - traefik_proxy
    ports:
     - "1883:1883"
    volumes:
      - $USERDIR/docker/mqtt:/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

## SmartThings MQTT Bridge
  mqtt_bridge:
    container_name: mqtt_bridge
    image: stjohnjohnson/smartthings-mqtt-bridge:latest
    restart: always
    networks:
      - traefik_proxy
    ports:
     - "8082:8080"
    volumes:
      - $USERDIR/docker/mqtt_bridge:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
#    labels:
#      - "traefik.enable=true"
#      ## HTTP Routers
#      - "traefik.http.routers.wetty-rtr.entrypoints=https"
#      - "traefik.http.routers.wetty-rtr.rule=Host(`wetty.$DOMAINNAME`)"
#      - "traefik.http.routers.wetty-rtr.tls=true"
#      - "traefik.http.routers.wetty-rtr.tls.certresolver=dns-cloudflare"
#      ## Middlewares
#      - "traefik.http.routers.wetty-rtr.middlewares=secure-chain@file"
#      ## HTTP Services
#      - "traefik.http.routers.wetty-rtr.service=wetty-svc"
#      - "traefik.http.services.wetty-svc.loadbalancer.server.port=3000"

networks:
  traefik_proxy:
    external: true
