version: "3.7"
services:

## SmartThings MQTT Bridge
  mqtt-bridge:
    container_name: mqtt-bridge
    image: stjohnjohnson/smartthings-mqtt-bridge:latest
    restart: always
    mac_address: $BRIDGE_MAC
    networks:
      mqtt:
        ipv4_address: 192.168.252.50
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/mqtt-bridge:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  mqtt:
    external: true
