version: "3.7"
services:

## NextCloud – Your Own Cloud Storage

  ## Suggested way to create NextCloud database using MariaDB
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE nextcloud CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'nextcloud.mariadb'IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit
  ## When signing in under Storage & database select MySQL/MariaDB and enter:
    # Database user: your db user (nextcloud)
    # Database password: your db password (<password>)
    # Database name: your db name (nextcloud)
    # localhost: mariadb:3306

  ## If you have a Redis server you can connect to it in $USERDIR/docker/nextcloud/www/nextcloud/config/config.php: (Optional)
    ## Add the following lines after " 'memcache.local' => '\\OC\\Memcache\\APCu', "
    # 'memcache.distributed' => '\\OC\\Memcache\\Redis',
    # 'memcache.locking' => '\\OC\\Memcache\\Redis',
    # 'redis' => array(
    #     'host' => 'redis',
    #     'port' => 6379,
    # ),

  ## An example to run occ commands:
    # docker exec -it nextcloud sudo --user abc php7 /config/www/nextcloud/occ db:add-missing-indices

  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud:latest
    restart: always
    networks:
      - traefik_proxy
      - mariadb
#    ports:
#      - "443:443"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/nextcloud:/config
      - /mnt/storage/files/nextcloud:/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      ## TCP Routers
      - "traefik.tcp.routers.nextcloud-tcp.entrypoints=https"
      - "traefik.tcp.routers.nextcloud-tcp.rule=HostSNI(`nextcloud.$DOMAINNAME`)"
      - "traefik.tcp.routers.nextcloud-tcp.tls.certresolver=dns-cloudflare"
      - "traefik.tcp.routers.nextcloud-tcp.tls.passthrough=true"
      ## TCP Services
      - "traefik.tcp.routers.nextcloud-tcp.service=nextcloud-tcp-svc"
      - "traefik.tcp.services.nextcloud-tcp-svc.loadbalancer.server.port=443"

## Collabora - Document Server
  # Admin console at https://<CODE-domain>/loleaflet/dist/admin/admin.html
  code:
    container_name: code
    image: collabora/code:latest
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "9980:9980"
#    security_opt:
#      - no-new-privileges:true
    cap_add:
     - MKNOD
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - username=$MY_USERNAME
      - password=$MY_PASSWORD
      - domain=nextcloud.$DOMAINNAME #$MY_CODE_DOMAIN #<your-NEXTCLOUD-dot-escaped-domain>
      - VIRTUAL_HOST=code.$DOMAINNAME
      - LETSENCRYPT_HOST=code.$DOMAINNAME
#      - server_name=code.$DOMAINNAME
      - extra_params=--o:ssl.enable=false --o:ssl.termination=true
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.code-rtr.entrypoints=https"
      - "traefik.http.routers.code-rtr.rule=Host(`code.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.code-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.code-rtr.service=code-svc"
      - "traefik.http.services.code-svc.loadbalancer.server.port=9980"

networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
