version: "3.7"
services:

## NextCloud – Your Own Cloud Storage

  ## Suggested to create NextCloud database using MariaDB
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE nextcloud CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'nextcloud.traefik_proxy'IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit
  ## When signing in under Storage & database select MySQL/MariaDB and enter:
    # Database user: your db user (nextcloud)
    # Database password: your db password (<password>)
    # Database name: your db name (nextcloud)
    # localhost: mariadb:3306

  ## If you have header issues in the settings dashboard, fix by editing $USERDIR/docker/nextcloud/www/nextcloud/config/config.php
    ## Add these lines within the config array:
    # 'forwarded_for_headers' =>
    # array (
    #   0 => 'HTTP_X_FORWARDED_FOR',
    # ),

  ## If you have the "bigint" issue:
    # docker exec -it nextcloud sh
    # sudo -u abc php /config/www/nextcloud/occ db:convert-filecache-bigint
    # exit

  ## If you have a Redis server you can connect to it in $USERDIR/docker/nextcloud/www/nextcloud/config/config.php: (Optional)
    ## Add the following lines after " 'memcache.local' => '\\OC\\Memcache\\APCu', "
    # 'memcache.distributed' => '\\OC\\Memcache\\Redis',
    # 'memcache.locking' => '\\OC\\Memcache\\Redis',
    # 'redis' => array(
    #     'host' => 'redis',
    #     'port' => 6379,
    # ),

  nextcloud:
    container_name: nextcloud
    image: linuxserver/nextcloud
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "7443:443"
    volumes:
      - /mnt/storage/files/nextcloud:/data
      - $USERDIR/docker/nextcloud:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.nextcloud.entrypoints=https
      - traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAINNAME`)
      - traefik.http.routers.nextcloud.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.nextcloud.middlewares=nextcloud-headers
      - traefik.http.middlewares.nextcloud-headers.headers.SSLHost=nextcloud.$DOMAINNAME
      - traefik.http.routers.nextcloud.middlewares=plex-redirect
      - traefik.http.middlewares.nextcloud-redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.http.middlewares.nextcloud-redirect.redirectregex.replacement=https://$$1/remote.php/dav/
      - traefik.http.middlewares.nextcloud-redirect.redirectregex.permanent=true
      ## Middlewares - Chain
      - traefik.http.routers.nextcloud.middlewares=noauth-chain@file
      ## Services
      - traefik.http.routers.nextcloud.service=nextcloud
      - traefik.http.services.nextcloud.loadbalancer.server.port=443

## OnlyOffice - Document Server for NextCloud
  # Add ONLYOFFICE to NextCloud and enter server address in settings
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver
    stdin_open: "true"
    tty: "true"
    restart: always
    networks:
      traefik_proxy:
        ipv4_address: 192.168.1.236
#    ports:
#      - "80:80"
#      - "443:443"
    volumes:
      - onlyoffice_logs:/var/log/onlyoffice
      - onlyoffice_fonts:/usr/share/fonts/truetype/custom
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.onlyoffice.entrypoints=https
      - traefik.http.routers.onlyoffice.rule=Host(`onlyoffice.$DOMAINNAME`)
      - traefik.http.routers.onlyoffice.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.onlyoffice.middlewares=onlyoffice-headers
      - traefik.http.middlewares.onlyoffice-headers.headers.SSLHost=onlyoffice.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.onlyoffice.middlewares=noauth-chain@file
      ## Services
      - traefik.http.routers.onlyoffice.service=onlyoffice
      - traefik.http.services.onlyoffice.loadbalancer.server.port=80

volumes:
  onlyoffice_logs:
  onlyoffice_fonts:

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
