version: "3.7"
services:

## Ombi – Media Request App
  ombi:
    container_name: ombi
    image: linuxserver/ombi:latest
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "3579:3579"
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${USERDIR}/docker/ombi:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.ombi-rtr.entrypoints=https"
      - "traefik.http.routers.ombi-rtr.rule=Host(`ombi.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.ombi-rtr.middlewares=secure-headers@file,rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.ombi-rtr.service=ombi-svc"
      - "traefik.http.services.ombi-svc.loadbalancer.server.port=3579"

networks:
  traefik_proxy:
    external: true
