version: "3.7"
services:

## OpenBazaar - A Free Online Marketplace
  openbazaar:
    container_name: openbazaar
    image: openbazaar/server:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
    ports:
      - "4001:4001"
      - "4002:4002"
      - "9005:9005"
#    security_opt:
#      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/openbazaar:/var/lib/openbazaar
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.openbazaar-rtr.entrypoints=https"
      - "traefik.http.routers.openbazaar-rtr.rule=HostHeader(`openbazaar.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.openbazaar-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.openbazaar-rtr.service=openbazaar-svc"
      - "traefik.http.services.openbazaar-svc.loadbalancer.server.port=3000"

networks:
  traefik_proxy:
    external: true
