version: "3.7"
services:

## Ouroboros
  # https://hub.docker.com/r/pyouroboros/ouroboros/
  # https://github.com/pyouroboros/ouroboros/wiki
  ouroboros:
    container_name: ouroboros
    image: pyouroboros/ouroboros:latest
    restart: always
    networks:
      - traefik_proxy
      - docker_socket
#    ports:
#      - "192.168.253.253:2375:2375"
    security_opt:
      - no-new-privileges:true
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro # Connect to docker-socket-proxy tcp://docker-socket-proxy:2375
    environment:
      - TZ=$TZ
      - CLEANUP=true
      - CRON="0 4 * * *"
#      - INTERVAL=3600 # Comment out if using Cron
#      - RUN_ONCE=true # Default false
      - LOG_LEVEL=info
      - SELF_UPDATE=true
#      - IGNORE=mongo influxdb postgres mariadb
      - NOTIFIERS=$SLACK_NOTIFY # Slack Webhook URL
      - DOCKER_SOCKETS=tcp://docker-socket-proxy:2375

networks:
  traefik_proxy:
    external: true
  docker_socket:
    external: true
