version: "3.7"
services:

## MusicBrainz Picard – Music Management
  picard:
    container_name: picard
    image: mikenye/picard
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "5800:5800"
    volumes:
      - /mnt/storage/music:/storage:rw
      - $USERDIR/docker/picard:/config:rw
    environment:
      - USER_ID=$PUID
      - GROUP_ID=$PGID
      - TZ=$TZ
      - UMASK=002
      - DISPLAY_WIDTH=1280
      - DISPLAY_HEIGHT=768
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.picard.entrypoints=https
      - traefik.http.routers.picard.rule=Host(`picard.$DOMAINNAME`)
      - traefik.http.routers.picard.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.picard.middlewares=picard-headers
      - traefik.http.middlewares.picard-headers.headers.SSLHost=picard.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.picard.middlewares=vnc-chain@file
      ## Services
      - traefik.http.routers.picard.service=picard
      - traefik.http.services.picard.loadbalancer.server.port=5800

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
