version: "3.7"
services:

## Postgres - Database

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    networks:
      - traefik_proxy
#    ports:
#      - "5432:5432"
    volumes:
      - $USERDIR/docker/postgres:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=$PG_ROOT_PASSWORD
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## TCP
      - traefik.tcp.routers.postgres-rtr.entrypoints=postgres-port
      - traefik.tcp.routers.postgres-rtr.tls=true
      - traefik.tcp.routers.postgres-rtr.rule=HostSNI(`*`)
      - traefik.tcp.routers.postgres-rtr.service=postgres-svc
      - traefik.tcp.services.postgres-svc.loadbalancer.server.port=3306

## PGAdmin - Postgres Admin Tool

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgres
    networks:
      - traefik_proxy
#    ports:
#      - "80:80"
#      - "443:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=$MY_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$MY_PASSWORD
#      - PGADMIN_ENABLE_TLS= # Can configure with certs
      - PGADMIN_LISTEN_PORT=80 # Can configure with certs
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.pgadmin-rtr.entrypoints=https
      - traefik.http.routers.pgadmin-rtr.rule=Host(`pgadmin.$DOMAINNAME`)
      - traefik.http.routers.pgadmin-rtr.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.pgadmin-rtr.middlewares=pgadmin-headers
      - traefik.http.middlewares.pgadmin-headers.headers.SSLHost=pgadmin.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.pgadmin-rtr.middlewares=secure-chain@file
      ## Services
      - traefik.http.routers.pgadmin-rtr.service=pgadmin-svc
      - traefik.http.services.pgadmin-svc.loadbalancer.server.port=80

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
