version: "3.7"
services:

## ProjectSend - WeTransfer/File Sharing

  ## Suggested procedure to create your ProjectSend Database:
  ## Change the <password>
    # docker exec -it mariadb mysql -uroot -p$MYSQL_ROOT_PASSWORD
    # CREATE DATABASE projectsend CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
    # GRANT ALL PRIVILEGES ON projectsend.* TO 'projectsend'@'projectsend.mariadb' IDENTIFIED BY '<password>';
    # FLUSH PRIVILEGES;
    # exit

  ## Start container and enter database information during install process
    # Replace localhost with "mariadb:3306"

  projectsend:
    container_name: projectsend
    image: linuxserver/projectsend:latest
    restart: always
    networks:
      - traefik_proxy
      - mariadb
#    ports:
#      - "9980:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/projectsend:/config
      - /mnt/storage/files/PROJECTSEND:/data
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MAX_UPLOAD=30720 # 30GB
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.projectsend-rtr.entrypoints=https"
      - "traefik.http.routers.projectsend-rtr.rule=Host(`send.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.projectsend-rtr.middlewares=secure-headers@file,rate-limit@file"
      ## HTTP Services
      - "traefik.http.routers.projectsend-rtr.service=projectsend-svc"
      - "traefik.http.services.projectsend-svc.loadbalancer.server.port=80"

networks:
  traefik_proxy:
    external: true
  mariadb:
    external: true
