version: "3.7"
services:

## qBittorrent with VPN – Bittorrent Downloader
  # mkdir $USERDIR/docker/qbittorrent
  # mkdir $USERDIR/docker/qbittorrent/openvpn
  # Place ovpn file in $USERDIR/docker/qbittorrent/openvpn
  # If you can't see text in the WebUI go to your qbittorrent.conf file and add "en" to the Locale setting so it looks like this: General\Locale=en

  qbittorrent:
    container_name: qbittorrent
    image: markusmcnugen/qbittorrentvpn
    restart: always
    networks:
      - traefik_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
#    ports:
#      - "8022:8080"
#      - "8999:8999"
#      - "8999:8999/udp"
    volumes:
      - $USERDIR/dwnloads:/downloads
      - /mnt/storage:/mnt/storage
      - $USERDIR/docker/qbittorrent:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - VPN_ENABLED=yes
      - VPN_USERNAME=$PIA_USER
      - VPN_PASSWORD=$PIA_PASS
      - LAN_NETWORK=192.168.1.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - UMASK=002
      ## Add these to your .ovpn file:
#      - VPN_OPTIONS=--inactive 3600 --ping 10 --ping-exit 60 --auth-nocache
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.qbittorrent.entrypoints=https
      - traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.$DOMAINNAME`)
      - traefik.http.routers.qbittorrent.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.qbittorrent.middlewares=qbittorrent-headers
      - traefik.http.middlewares.qbittorrent-headers.headers.SSLHost=qbittorrent.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.qbittorrent.middlewares=vnc-chain-nocookie@file
      ## Services
      - traefik.http.routers.qbittorrent.service=qbittorrent
      - traefik.http.services.qbittorrent.loadbalancer.server.port=8080

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
