version: "3.7"
services:

## Soulseek - P2P Media Service
  soulseek:
    container_name: soulseek
    image: realies/soulseek:latest
    restart: always
    networks:
      - traefik_proxy
#    network_mode: "container:qbittorrent"
    ports:
      - "6080:6080"
#    security_opt:
#      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/soulseek/data:/data/.config
      - $USERDIR/dwnloads/completed:/data/Soulseek Downloads/complete
      - $USERDIR/dwnloads/temp:/data/Soulseek Downloads/downloading
      - /mnt/storage/music/music:/Music:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - puid=$PUID
      - pgid=$PGID
      - resolution=1600x720
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.soulseek-rtr.entrypoints=https"
      - "traefik.http.routers.soulseek-rtr.rule=Host(`soulseek.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.soulseek-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.soulseek-rtr.service=soulseek-svc"
      - "traefik.http.services.soulseek-svc.loadbalancer.server.port=6080"

networks:
  traefik_proxy:
    external: true
