version: "3.7"
services:

## Soulseek - P2P Media Service
  soulseek:
    container_name: soulseek
    image: realies/soulseek
    restart: always
    network_mode: "container:qbittorrent"
#    ports:
#      - "6080:6080"
    volumes:
      - soulseekdata:/root
      - /mnt/storage/music/to_be_tagged:/root/Soulseek Downloads
      - /mnt/storage/music/music:/Music
      - /etc/localtime:/etc/localtime:ro
    environment:
      - resolution=1280x720
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      ## HTTPS entrypoint
      - traefik.http.routers.soulseek.entrypoints=https
      - traefik.http.routers.soulseek.rule=Host(`soulseek.$DOMAINNAME`)
      - traefik.http.routers.soulseek.tls.certresolver=cloudflare
      ## Middlewares - Unique
      - traefik.http.routers.soulseek.middlewares=soulseek-headers
      - traefik.http.middlewares.soulseek-headers.headers.SSLHost=soulseek.$DOMAINNAME
      ## Middlewares - Chain
      - traefik.http.routers.soulseek.middlewares=vnc-chain@file
      ## Services
      - traefik.http.routers.soulseek.service=soulseek
      - traefik.http.services.soulseek.loadbalancer.server.port=6080

volumes:
  soulseekdata:
