version: "3.7"
services:

## StatPing - Status Page & Monitoring Server
  # Login: admin / admin

  statping:
    container_name: statping
    image: hunterlong/statping:latest
    restart: unless-stopped
    networks:
      - traefik_proxy
      - postgres
#    ports:
#      - "4480:8080"
    volumes:
      - $USERDIR/docker/statping/config:/app
    environment:
      - DB_CONN=postgres
      - DB_HOST=postgres
      - DB_USER=statping
      - DB_PASS=$PG_PASSWORD
      - DB_DATABASE=statping
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.statping-rtr.entrypoints=https"
      - "traefik.http.routers.statping-rtr.rule=Host(`statping.$DOMAINNAME`)"
      - "traefik.http.routers.statping-rtr.tls=true"
      - "traefik.http.routers.statping-rtr.tls.certresolver=dns-cloudflare"
      ## Middlewares
      - "traefik.http.routers.statping-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.statping-rtr.service=statping-svc"
      - "traefik.http.services.statping-svc.loadbalancer.server.port=8080"

networks:
  traefik_proxy:
    external: true
  postgres:
    external: true
