version: "3.7"
services:

## Tautulli – Monitoring Plex Usage
  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest
    restart: always
    networks:
      traefik_proxy:
        ipv4_address: 192.168.50.243
#    ports:
#      - "8181:8181"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/docker/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro # Plex Log Directory
      - $USERDIR/docker/tautulli/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
      - "traefik.http.routers.tautulli-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.tautulli-rtr.middlewares=secure-chain@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
      ## API
      - "traefik.http.routers.tautulliAPI-rtr.entrypoints=https"
      - "traefik.http.routers.tautulliAPI-rtr.rule=Host(`tautulli.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$TAUTULLI_DEVICE_KEY`) || Query(`apikey`, `$TAUTULLI_DEVICE_KEY`))"
      - "traefik.http.routers.tautulliAPI-rtr.priority=20"
      - "traefik.http.routers.tautulliAPI-rtr.middlewares=basic-chain@file"
      - "traefik.http.routers.tautulliAPI-rtr.service=tautulli-svc"

networks:
  traefik_proxy:
    external: true
